# Generated by Django 2.1.2 on 2018-10-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cust_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cust_name',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
